// Export all widgets
export * from './CalendarWidget';
export * from './FavoriteLinksWidget';
export * from './NotificationsWidget';
export * from './QuickActionsWidget';
export * from './RecentActivityWidget';
export * from './ScratchPadWidget';
export * from './StatisticsWidget';
export * from './TaskListWidget';
export * from './TeamStatusWidget';
export * from './WeatherWidget';
export * from './SharingWidget';
export * from './DigitalAssetsWidget';
export * from './SecurityScoreWidget';
export * from './UpcomingAppointmentsWidget';
export * from './ImportantDocumentsWidget';
export * from './DeputyAccessWidget';
export * from './IDecideScoreWidget';
export * from './RssFeedWidget';